Logging:
  Format: '%(asctime)s [%(name)s] %(levelname)-8s %(message)s'
  Level: DEBUG

Database:
  Name: alertos
  ConnectionString: 'mongodb://root:root@mongo:27017'

Stocks:
  Provider: Schwab
  SubscriptionsSource: alerts

Schwab:
  # Allows up to 120 requests per second
  # Set equal or greater to the least subscription frequency
  # Set to an integer divisor of all subscription frequencies
  MarketDataUpdateIntervalSecs: 1