# syntax=docker/dockerfile:1
FROM python:3.10-alpine
WORKDIR /code
RUN apk add --no-cache gcc musl-dev linux-headers
COPY requirements-stocksource.txt requirements-stocksource.txt
RUN pip install -r requirements-stocksource.txt
WORKDIR /code/src
# COPY . .
ENTRYPOINT ["python", "-u", "stock_producer.py"]  # -u means unbuffered for print output to go to docker logs
